baseURL = 'https://hormigue.ar/'
languageCode = 'es-ar'
title = 'Hormigueo'
theme = 'hugo-simple-sections'

[params]
    description = "Bitácora de análisis político y sindical"
    
    # Estos son tus famosos bloques de inicio
    sections = [
        { name = "Bitácora UNaM", content = "Crónicas de la burocracia en Misiones.", url = "/posts", button = "Entrar al Búnker" },
        { name = "Laboratorio IA", content = "Experimentos con redes neuronales y literatura.", url = "/recursos", button = "Ver Herramientas" },
        { name = "Archivo Hormigueo", content = "Relatos y pesimismo alegre.", url = "/archivo", button = "Leer Todo" }
    ]
